version: '3.8'

services:

  redis:
    image: redis:7.2-alpine
    container_name: redis
    networks:
      - net

  backend:
    build: .
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - net

networks:
  net: